Updated structer of project and settings CI/CD

diff --git a/.github/workflows/classroom.yml b/.github/workflows/classroom.yml
--- a/.github/workflows/classroom.yml
+++ b/.github/workflows/classroom.yml
@@ -6,40 +6,109 @@ on:
   pull_request:
     branches:
       - master
+
 jobs:
   build:
-    name: Autograding
+    name: Build Project
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
         with:
           fetch-depth: 0
 
-      # TODO build, test and deploy project
-      - name: Build Docker image
-        run: docker build . --file Dockerfile --tag rsoi-lab1-app
+      - name: Build dockerfile for app
+        run: |
+          docker build -t person:latest ./ --target=release
+          docker save person:latest > person.tar
+      - uses: actions/upload-artifact@v4 
+        with: 
+          name: person-artefact 
+          path: person.tar
+      
+      - name: Build dockerfile for tests
+        run: |
+          docker build -t person-tests:latest ./ --target=builder
+          docker save person-tests:latest > person-tests.tar
+      - uses: actions/upload-artifact@v4 
+        with: 
+          name: person-tests-artefact 
+          path: person-tests.tar
+
+  test:
+    name: Test Project
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      
+      - uses: actions/download-artifact@v4
+        with: 
+          name: person-tests-artefact 
 
       - name: Run Unit Tests
-        run: docker run --rm --network host -e DATABASE_URL="postgresql://program:test@localhost:5432/persons" rsoi-lab1-app pytest
+        run: |
+          docker load < person-tests.tar
+          docker compose -f ./docker-compose.tests.yml --project-directory ./ up --exit-code-from person_service_tests
+          if [[ 0 == $? ]]
+          then
+            echo "TESTS_STATUS=success" >> $GITHUB_ENV
+          else
+            echo "TESTS_STATUS=failed" >> $GITHUB_ENV
+          fi
 
-      - name: Run API Tests
-        uses: matt-ball/newman-action@master
-        with:
-          collection: postman/[inst] Lab1.postman_collection.json
-          environment: postman/[inst][heroku] Lab1.postman_environment.json
-          delayRequest: 100
-          reporters: '[ "cli" ]'
+  # deploy:
+  #   name: Deploy Project
+  #   runs-on: ubuntu-latest
+  #   needs: test
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #       with:
+  #         fetch-depth: 0
+      
+  #     - uses: actions/download-artifact@v4
+  #       with: 
+  #         name: person-artefact 
 
-      - name: Autograding
-        uses: education/autograding@v1
-        continue-on-error: true
+  #     - name: Load To Server
+  #       run: |
+  #         sshpass -p ${{ secrets.SERVER_PASSWORD }} scp -o StrictHostKeyChecking=no person.tar ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP_ADDRESS }}:~/
+  #         sshpass -p ${{ secrets.SERVER_PASSWORD }} scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP_ADDRESS }}:~/
+  #         sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP_ADDRESS }} mkdir -p postgres
+  #         sshpass -p ${{ secrets.SERVER_PASSWORD }} scp -o StrictHostKeyChecking=no postgres/10-create-user-and-db.sql ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP_ADDRESS }}:~/postgres
 
-      - name: Github auto grader mark
-        uses: Romanow/google-sheet-autograder-marker@v1.0
-        with:
-          google_token: ${{secrets.GOOGLE_API_KEY}}
-          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
-          homework_number: 1
-          user_column: 'D'
-          column_offset: 'F'
-          mark: "'+"
+  #         sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP_ADDRESS }} docker load -i person.tar
+  #         sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP_ADDRESS }} docker-compose up -d
+
+
+  # integration-tests:
+  #   name: Autograding
+  #   runs-on: ubuntu-latest
+  #   needs: deploy
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #       with:
+  #         fetch-depth: 0
+
+  #     - name: Run API Tests
+  #       uses: matt-ball/newman-action@master
+  #       with:
+  #         collection: postman/[inst] Lab1.postman_collection.json
+  #         environment: postman/[inst][heroku] Lab1.postman_environment.json
+  #         delayRequest: 100
+  #         reporters: '[ "cli" ]'
+
+  #     - name: Autograding
+  #       uses: education/autograding@v1
+  #       continue-on-error: true
+
+  #     - name: Github auto grader mark
+  #       uses: Romanow/google-sheet-autograder-marker@v1.0
+  #       with:
+  #         google_token: ${{secrets.GOOGLE_API_KEY}}
+  #         sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
+  #         homework_number: 1
+  #         user_column: 'D'
+  #         column_offset: 'F'
+  #         mark: "'+"
